//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pajonos.Shleken.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public string Members { get; set; }
        public string Agenda { get; set; }
        public string Actions { get; set; }
        public string Location { get; set; }
        public int UserId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
