//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this Files may cause unexpected behavior in your application.
//     Manual changes to this Files will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

