//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pajonos.Shleken.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksRoles
    {
        public int RoleId { get; set; }
        public int TaskId { get; set; }
        public int Value { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
